### ISSUE TITLE
"pihole -up" not updating to latest version (only FTL was updated)

### ISSUE THREAD

**Issue by FDisk80** [DesktopECHO/Pi-hole-for-Android#10]
[android@localhost ~]$ **pihole -v**
Pi-hole version is v5.8.1 **(Latest: v5.9)**
AdminLTE version is v5.10.1 **(Latest: v5.11)**
FTL version is v5.14 **(Latest: v5.14)**

[android@localhost ~]$ **pihole -up**
[✓] Checking for git
[✓] Checking for iproute
[✓] Checking for newt
[✓] Checking for procps-ng
[✓] Checking for which
[✓] Checking for chkconfig
[✓] Checking for ca-certificates
[i] Checking for updates...
[i] Pi-hole Core: up to date
[i] Web Interface: up to date
[i] FTL: up to date
[✓] Everything is up to date!

**Comment by Dynasty-Dev** [comment]
Run p4a-install it seems it’s a bug with pihole

**Comment by DesktopECHO** [comment]
You can also try installing an updated version of Git at [CentOS7-ARMv7](https://github.com/DesktopECHO/CentOS7-ARMv7)

That seems to have worked for me but the Web admin pages are still showing incorrectly that there are packages out of date.

**Comment by ashishkotnala29** [comment]
This was an upstream bug from pihole with v5.8 which is fixed with v5.9 but anyone who has v5.8.x with git v1.8 will have issue updating to v5.9.
As suggested either upgrade git or reinstall pihole.

**Comment by FDisk80** [comment]
> This was an upstream bug from pihole with v5.8 which is fixed with v5.9 but anyone who has v5.8.x with git v1.8 (most CentOS7 users) will have issue updating to v5.9. As suggested either upgrade git or reinstall pihole.

What is the proper way updating git for CentOS7-ARMv7? I'm getting all kind of errors.

**Comment by ashishkotnala29** [comment]
https://forum.xda-developers.com/t/dev-root-pi-hole-for-android-deploy-pi-hole-dns-server-to-any-android-4-x-device.4332889/post-86299353

**Comment by FDisk80** [comment]
> https://forum.xda-developers.com/t/dev-root-pi-hole-for-android-deploy-pi-hole-dns-server-to-any-android-4-x-device.4332889/post-86299353

Still no go.

Did:
```
sudo yum remove -y git
sudo yum clean all
sudo yum install -y emacs-filesystem pcre2
```

Then tried to install only git, git-core, git-core-doc and perl-Git from http://desktopecho.com/CentOS7-ARMv7 with "sudo yum install -y". Got a bunch of errors.

Now "git --version" shows "git version 2.34.1"

But when Running "pihole -up" I get those errors.

```
  [android@localhost ~]$ pihole -up
  [i] Checking for git (will be installed)
  [✓] Checking for iproute
  [✓] Checking for newt
  [✓] Checking for procps-ng
  [✓] Checking for which
  [✓] Checking for chkconfig
  [✓] Checking for ca-certificates
  [i] Processing yum install(s) for: git, please wait...

Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: quantum-mirror.hu
 * extras: quantum-mirror.hu
 * remi: remi.mivzakim.net
 * updates: quantum-mirror.hu
Resolving Dependencies
--> Running transaction check
---> Package git.armv7hl 0:1.8.3.1-23.el7_8 will be installed
--> Processing Dependency: perl-Git = 1.8.3.1-23.el7_8 for package: git-1.8.3.1-23.el7_8.armv7hl
--> Processing Dependency: perl(Git) for package: git-1.8.3.1-23.el7_8.armv7hl
--> Running transaction check
---> Package perl-Git.noarch 0:1.8.3.1-23.el7_8 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

======================================================================================== Package            Arch              Version                      Repository      Size
========================================================================================Installing:
 git                armv7hl           1.8.3.1-23.el7_8             base           4.1 M
Installing for dependencies:
 perl-Git           noarch            1.8.3.1-23.el7_8             base            56 k

Transaction Summary
========================================================================================Install  1 Package (+1 Dependent package)

Total download size: 4.1 M
Installed size: 21 M
Downloading packages:
(1/2): perl-Git-1.8.3.1-23.el7_8.noarch.rpm                      |  56 kB  00:00:02
(2/2): git-1.8.3.1-23.el7_8.armv7hl.rpm                          | 4.1 MB  00:00:04
----------------------------------------------------------------------------------------Total                                                      969 kB/s | 4.1 MB  00:04
Running transaction check
Running transaction test


Transaction check error:
  file /usr/bin/git from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/bin/git-receive-pack from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-receive-pack from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/bin/git-shell from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-shell from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/bin/git-upload-archive from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-upload-archive from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/bin/git-upload-pack from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-upload-pack from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-add from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-am from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-annotate from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-apply from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-archive from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-bisect from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-bisect--helper from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-blame from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-branch from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-bundle from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-cat-file from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-check-attr from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-check-ignore from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-check-ref-format from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-checkout from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-checkout-index from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-cherry from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-cherry-pick from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-clean from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-clone from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-column from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-commit from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-commit-tree from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-config from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-count-objects from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-credential from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-credential-cache from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-credential-cache--daemon from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-credential-store from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-describe from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-diff from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-diff-files from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-diff-index from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-diff-tree from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-difftool from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-difftool--helper from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-fast-export from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-fast-import from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-fetch from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-fetch-pack from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-fmt-merge-msg from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-for-each-ref from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-format-patch from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-fsck from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-fsck-objects from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-gc from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-get-tar-commit-id from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-grep from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-hash-object from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-help from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-http-backend from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-http-fetch from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-http-push from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-imap-send from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-index-pack from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-init from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-init-db from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-log from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-ls-files from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-ls-remote from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-ls-tree from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-mailinfo from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-mailsplit from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-merge from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-merge-base from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-merge-file from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-merge-index from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-merge-octopus from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-merge-one-file from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-merge-ours from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-merge-recursive from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-merge-resolve from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-merge-subtree from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-merge-tree from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-mergetool from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-mergetool--lib from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-mktag from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-mktree from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-mv from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-name-rev from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-notes from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-pack-objects from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-pack-redundant from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-pack-refs from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-patch-id from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-prune from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-prune-packed from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-pull from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-push from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-quiltimport from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-read-tree from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-rebase from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-reflog from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-remote from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-remote-ext from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-remote-fd from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-remote-ftp from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-remote-ftps from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-remote-http from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-remote-https from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-repack from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-replace from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-rerere from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-reset from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-rev-list from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-rev-parse from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-revert from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-rm from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-send-pack from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-sh-i18n from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-sh-i18n--envsubst from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-sh-setup from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-shortlog from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-show from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-show-branch from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-show-index from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-show-ref from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-stage from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-stash from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-status from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-stripspace from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-submodule from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-submodule--helper from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-symbolic-ref from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-tag from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-unpack-file from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-unpack-objects from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-update-index from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-update-ref from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-update-server-info from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-var from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-verify-pack from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-verify-tag from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-web--browse from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-whatchanged from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/git-write-tree from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/mergetools/araxis from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/mergetools/codecompare from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/mergetools/deltawalker from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/mergetools/diffuse from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/mergetools/ecmerge from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/mergetools/emerge from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/mergetools/kdiff3 from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/mergetools/kompare from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/mergetools/meld from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/mergetools/opendiff from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/mergetools/tkdiff from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/mergetools/tortoisemerge from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/mergetools/vimdiff from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/libexec/git-core/mergetools/xxdiff from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/share/git-core/contrib/completion/git-completion.tcsh from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/share/git-core/contrib/completion/git-prompt.sh from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/share/git-core/contrib/hooks/post-receive-email from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/share/git-core/contrib/hooks/pre-auto-gc-battery from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/share/git-core/templates/hooks/applypatch-msg.sample from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/share/git-core/templates/hooks/pre-applypatch.sample from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/share/git-core/templates/hooks/pre-commit.sample from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/share/git-core/templates/hooks/pre-push.sample from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/share/git-core/templates/hooks/update.sample from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/share/locale/de/LC_MESSAGES/git.mo from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/share/locale/is/LC_MESSAGES/git.mo from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/share/locale/it/LC_MESSAGES/git.mo from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/share/locale/pt_PT/LC_MESSAGES/git.mo from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/share/locale/sv/LC_MESSAGES/git.mo from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/share/locale/vi/LC_MESSAGES/git.mo from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/share/locale/zh_CN/LC_MESSAGES/git.mo from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-2.34.1-1.el7.armv7hl
  file /usr/share/man/man1/git-add.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-am.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-annotate.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-apply.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-archive.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-bisect.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-blame.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-branch.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-bundle.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-cat-file.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-check-attr.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-check-ignore.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-check-ref-format.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-checkout-index.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-checkout.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-cherry-pick.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-cherry.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-clean.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-clone.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-column.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-commit-tree.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-commit.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-config.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-count-objects.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-credential-cache--daemon.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-credential-cache.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-credential-store.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-credential.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-describe.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-diff-files.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-diff-index.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-diff-tree.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-diff.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-difftool.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-fast-export.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-fast-import.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-fetch-pack.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-fetch.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-fmt-merge-msg.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-for-each-ref.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-format-patch.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-fsck-objects.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-fsck.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-gc.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-get-tar-commit-id.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-grep.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-hash-object.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-help.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-http-backend.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-http-fetch.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-http-push.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-imap-send.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-index-pack.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-init-db.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-init.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-log.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-ls-files.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-ls-remote.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-ls-tree.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-mailinfo.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-mailsplit.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-merge-base.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-merge-file.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-merge-index.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-merge-one-file.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-merge-tree.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-merge.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-mergetool--lib.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-mergetool.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-mktag.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-mktree.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-mv.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-name-rev.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-notes.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-pack-objects.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-pack-redundant.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-pack-refs.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-patch-id.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-prune-packed.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-prune.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-pull.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-push.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-quiltimport.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-read-tree.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-rebase.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-receive-pack.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-reflog.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-remote-ext.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-remote-fd.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-remote.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-repack.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-replace.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-rerere.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-reset.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-rev-list.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-rev-parse.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-revert.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-rm.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-send-pack.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-sh-i18n--envsubst.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-sh-i18n.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-sh-setup.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-shell.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-shortlog.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-show-branch.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-show-index.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-show-ref.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-show.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-stage.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-stash.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-status.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-stripspace.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-submodule.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-symbolic-ref.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-tag.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-unpack-file.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-unpack-objects.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-update-index.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-update-ref.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-update-server-info.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-upload-archive.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-upload-pack.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-var.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-verify-pack.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-verify-tag.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-web--browse.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-whatchanged.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git-write-tree.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man1/git.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man5/gitattributes.5.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man5/githooks.5.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man5/gitignore.5.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man5/gitmodules.5.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man5/gitrepository-layout.5.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man7/gitcli.7.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man7/gitcore-tutorial.7.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man7/gitcredentials.7.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man7/gitcvs-migration.7.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man7/gitdiffcore.7.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man7/gitglossary.7.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man7/gitnamespaces.7.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man7/gitrevisions.7.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man7/gittutorial-2.7.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man7/gittutorial.7.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/share/man/man7/gitworkflows.7.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-core-doc-2.34.1-1.el7.noarch
  file /usr/libexec/git-core/git-subtree from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-subtree-2.34.1-1.el7.armv7hl
  file /usr/share/man/man1/git-subtree.1.gz from install of git-1.8.3.1-23.el7_8.armv7hl conflicts with file from package git-subtree-2.34.1-1.el7.armv7hl

Error Summary
-------------
```

**Comment by ashishkotnala29** [comment]
> Then tried to install only git, git-core, git-core-doc and perl-Git from http://desktopecho.com/CentOS7-ARMv7 with "sudo yum install -y". Got a bunch of errors.

Try installing the RPMs the usual way using `rpm -Uvh *.rpm` after you remove stock git.

**Comment by FDisk80** [comment]
> > Then tried to install only git, git-core, git-core-doc and perl-Git from http://desktopecho.com/CentOS7-ARMv7 with "sudo yum install -y". Got a bunch of errors.
> 
> Try installing the RPMs the usual way using `sudo rpm -Uvh *.rpm` after you remove stock git. Also if you do get errors please post them. That'll be helpful.

Tried like this:

`sudo yum remove -y git
`

I get this:

```
Loaded plugins: fastestmirror
No Match for argument: git
No Packages marked for removal
```
---
`sudo yum clean all
`

I get this:

```
Loaded plugins: fastestmirror
Cleaning repos: base community-php74-testing epel extras remi updates
Cleaning up list of fastest mirrors
```
---
`sudo yum install -y emacs-filesystem pcre2
`

I get this:

```
Loaded plugins: fastestmirror
Determining fastest mirrors
 * base: ftp.bme.hu
 * extras: ftp.bme.hu
 * remi: remi.mivzakim.net
 * updates: ftp.bme.hu
base                                                             | 3.6 kB  00:00:00
community-php74-testing                                          | 3.8 kB  00:00:00
epel                                                             | 3.8 kB  00:00:00
extras                                                           | 2.9 kB  00:00:00
remi                                                             | 3.0 kB  00:00:00
updates                                                          | 2.9 kB  00:00:00
(1/9): base/7/armhfp/group_gz                                    | 153 kB  00:00:01
(2/9): community-php74-testing/group_gz                          |   20 B  00:00:02
(3/9): base/7/armhfp/primary_db                                  | 4.1 MB  00:00:02
(4/9): extras/7/armhfp/primary_db                                | 210 kB  00:00:00
(5/9): epel/group_gz                                             |  88 kB  00:00:02
(6/9): updates/7/armhfp/primary_db                               | 1.5 MB  00:00:00
(7/9): remi/primary_db                                           | 990 kB  00:00:01
(8/9): community-php74-testing/primary_db                        | 1.5 MB  00:00:06
(9/9): epel/primary_db                                           | 9.9 MB  00:00:13
Package 1:emacs-filesystem-24.3-23.el7.noarch already installed and latest version
Package pcre2-10.23-2.el7.armv7hl already installed and latest version
Nothing to do
```
---
`sudo rpm -Uvh http://desktopecho.com/CentOS7-ARMv7/git-2.34.1-1.el7.armv7hl.rpm`

Gives this error:
```
Retrieving http://desktopecho.com/CentOS7-ARMv7/git-2.34.1-1.el7.armv7hl.rpm
error: Failed dependencies:
        perl(Git) is needed by git-2.34.1-1.el7.armv7hl
        perl(Git::I18N) is needed by git-2.34.1-1.el7.armv7hl
        perl-Git = 2.34.1-1.el7 is needed by git-2.34.1-1.el7.armv7hl
```
---
`sudo rpm -Uvh http://desktopecho.com/CentOS7-ARMv7/git-core-2.34.1-1.el7.armv7hl.rpm`

Gives me this:
```
Retrieving http://desktopecho.com/CentOS7-ARMv7/git-core-2.34.1-1.el7.armv7hl.rpm
Preparing...                          ################################# [100%]
        package git-core-2.34.1-1.el7.armv7hl is already installed
```
---
`sudo rpm -Uvh http://desktopecho.com/CentOS7-ARMv7/git-core-doc-2.34.1-1.el7.noarch.rpm`

Gives me this:
```
Retrieving http://desktopecho.com/CentOS7-ARMv7/git-core-doc-2.34.1-1.el7.noarch.rpm
Preparing...                          ################################# [100%]
        package git-core-doc-2.34.1-1.el7.noarch is already installed
```
---
`sudo rpm -Uvh http://desktopecho.com/CentOS7-ARMv7/perl-Git-2.34.1-1.el7.noarch.rpm`

Gives me this:
```
Retrieving http://desktopecho.com/CentOS7-ARMv7/perl-Git-2.34.1-1.el7.noarch.rpm
error: Failed dependencies:
        git = 2.34.1-1.el7 is needed by perl-Git-2.34.1-1.el7.noarch
```

**Comment by ashishkotnala29** [comment]
Try this
`sudo rpm -Uvh http://desktopecho.com/CentOS7-ARMv7/perl-Git-2.34.1-1.el7.noarch.rpm --nodeps`
`sudo rpm -Uvh http://desktopecho.com/CentOS7-ARMv7/git-2.34.1-1.el7.armv7hl.rpm --nodeps`

then check
`git --version`

You should be good.

**Comment by FDisk80** [comment]
> Try this `sudo rpm -Uvh http://desktopecho.com/CentOS7-ARMv7/perl-Git-2.34.1-1.el7.noarch.rpm --nodeps` `sudo rpm -Uvh http://desktopecho.com/CentOS7-ARMv7/git-2.34.1-1.el7.armv7hl.rpm --nodeps`
> 
> then check `git --version`

Thank you! This worked.

```
 Update Complete!

  Current Pi-hole version is v5.9
  Current AdminLTE version is v5.11
  Current FTL version is v5.14
```
  
  ```
pihole -v

  Pi-hole version is v5.9 (Latest: v5.9)
  AdminLTE version is v5.11 (Latest: v5.11)
  FTL version is v5.14 (Latest: v5.14)
```

So all was needed is to skip the test of dependencies?

**Comment by ashishkotnala29** [comment]
Well... In your case, yes because you were installing the RPMs one by one. If you download all the RPMs in one directory and simply run `sudo rpm -Uvh *.rpm` it would detect dependent RPMs itself in the "install queue" and wouldn't complain.

On the other hand I hate when there are cyclic dependencies, goes to show the bad code architecture/structure.
Anyways, glad it worked out.

**Comment by youngt2** [comment]
So what is the proper way to update to the latest version? I'm a bit lost with .rpm and git versions...

**Comment by DesktopECHO** [comment]
`pihole -up` Should work ok, unless you installed this a few months ago, in which case you can just run `p4a-install` to force-update.

**Comment by youngt2** [comment]
Hmm. OK. The first time I tried it only updated FTL, but I reinstalled the whole image and this time it worked. Sorry!

**Comment by youngt2** [comment]
Alright - I was confused by the `pihole -up --check-only`
According to `pihole -v` I have:
```
  Pi-hole version is v5.8.1 (Latest: v5.9.1)
  AdminLTE version is v5.10.1 (Latest: v5.11)
  FTL version is v5.14 (Latest: v5.14)
```
Also, I get the 503 error as seen on another issue post. Perhaps it has to do with my screen going off though. If I stop and start the image it works again. I'll try leaving the screen on for awhile.

Any advice about the updating?

**Comment by DesktopECHO** [comment]
Run `sudo p4a-install` then verify you are up-to-date with `pihole -up --check-only`

**Comment by youngt2** [comment]
> Run `sudo p4a-install` then verify you are up-to-date with `pihole -up --check-only`

Looks good! Thank you so much
